### ISSUE TITLE
Tasks from recent review

### ISSUE THREAD

**Issue by rossbar** [numpy/user-survey-2020-details#12]
A listing of things to tackle from the most recent review. @InessaPawson please feel free to add anything I've missed.

 - [x] Add glossary of terms | See #14
 - [x] Modify plot color scheme. Branded colors + orange first | See #13 
 - [x] Reorganize menubar items | See #21 
    * Note: it would be a lot of effort to reorganize as the data loading for each notebook reflects the sequential structure of the underlying survey data. Existing sections could be renamed easily enough.
 - [x] Add acknowledgements | See #15
 - [x] Add methodology section
 - [x] Move narrative text from google doc to site source | See #18

**Comment by InessaPawson** [comment]
The to-do list has been captured correctly. Thank you, @rossbar!

**Comment by rossbar** [comment]
I'm pretty sure these were addressed - we can always revisit when reviewing prior to releasing the 2021 results.
